//! Minimal Executor — per AUDIT Pass 14 RT-003, Pass 15-16 verification gates
//! Implements DESIGN.md §4 Real-Time Guarantees, §15 Deep Dive Real-Time Scheduler
//! Status: SCAFFOLDED-IMPLEMENTED — single-process, deterministic, priority-based, deadline monitoring (not yet enforcement)
//! Would become real-time executor with CPU affinity, NUMA awareness, memory pools, interrupt handling, DMA coordination per DESIGN.md §15

use std::collections::{BinaryHeap, HashMap};
use std::sync::{Arc, atomic::{AtomicU64, Ordering}};
use std::time::{Duration, Instant};
use crate::{ExecutionClass, ChannelConfig};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TaskId(pub u64);

impl TaskId {
    pub fn new(id: u64) -> Self { Self(id) }
}

// Note: Eq/PartialEq compare ALL fields. The earlier manual impl only compared (priority, id),
// which was inconsistent with Ord (which also compares deadline) and violated the Ord contract
// (a == b must imply a.cmp(b) == Equal). That inconsistency could corrupt BinaryHeap ordering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CallbackDescriptor {
    pub id: TaskId,
    pub name: String,
    pub execution_class: ExecutionClass,
    pub priority: u8, // 0-255, 200+ reserved safety-critical per DESIGN.md §15.1
    pub deadline: Option<Duration>, // e.g., 1000us for control_loop
    pub period: Option<Duration>,   // e.g., 10ms for 100Hz
    pub cpu_affinity: Option<Vec<usize>>, // Pin to specific cores per DESIGN.md §15.1
}

impl PartialOrd for CallbackDescriptor {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for CallbackDescriptor {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        // Higher priority first (BinaryHeap is max-heap, so higher priority should be Greater)
        // Also earlier deadline first for same priority (EDF-like)
        // Finally tie-break by id to keep ordering total and consistent with Eq.
        match self.priority.cmp(&other.priority) {
            std::cmp::Ordering::Equal => {
                match (&self.deadline, &other.deadline) {
                    (Some(a), Some(b)) => match b.cmp(a) {
                        // Earlier deadline = Greater (pops first)
                        std::cmp::Ordering::Equal => self.id.cmp(&other.id),
                        ord => ord,
                    },
                    (Some(_), None) => std::cmp::Ordering::Greater,
                    (None, Some(_)) => std::cmp::Ordering::Less,
                    (None, None) => self.id.cmp(&other.id),
                }
            }
            ord => ord,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ExecutionStats {
    pub task_id: TaskId,
    pub execution_count: u64,
    pub total_execution_time: Duration,
    pub max_execution_time: Duration,
    pub min_execution_time: Duration,
    pub deadline_misses: u64,
    pub last_execution: Option<Instant>,
}

impl ExecutionStats {
    pub fn new(task_id: TaskId) -> Self {
        Self {
            task_id,
            execution_count: 0,
            total_execution_time: Duration::ZERO,
            max_execution_time: Duration::ZERO,
            min_execution_time: Duration::from_secs(1000),
            deadline_misses: 0,
            last_execution: None,
        }
    }

    pub fn record(&mut self, elapsed: Duration, deadline: Option<Duration>) {
        self.execution_count += 1;
        self.total_execution_time += elapsed;
        if elapsed > self.max_execution_time {
            self.max_execution_time = elapsed;
        }
        if elapsed < self.min_execution_time {
            self.min_execution_time = elapsed;
        }
        if let Some(dl) = deadline {
            if elapsed > dl {
                self.deadline_misses += 1;
            }
        }
        self.last_execution = Some(Instant::now());
    }

    pub fn avg_execution_time(&self) -> Duration {
        if self.execution_count == 0 {
            Duration::ZERO
        } else {
            self.total_execution_time / self.execution_count as u32
        }
    }
}

/// Minimal deterministic executor — single-threaded for now, would become multi-threaded with work-stealing, CPU affinity per §15
/// Status: SCAFFOLDED-IMPLEMENTED — priority-based ready queue, period handling (via next execution time), deadline monitoring (not enforcement)
pub struct Executor {
    tasks: HashMap<TaskId, CallbackDescriptor>,
    ready_queue: BinaryHeap<CallbackDescriptor>,
    execution_stats: HashMap<TaskId, ExecutionStats>,
    next_id: AtomicU64,
    start_time: Instant,
}

impl Executor {
    pub fn new() -> Self {
        Self {
            tasks: HashMap::new(),
            ready_queue: BinaryHeap::new(),
            execution_stats: HashMap::new(),
            next_id: AtomicU64::new(1),
            start_time: Instant::now(),
        }
    }

    /// Register callback descriptor — would be generated by #[nros::node] macro in real NROS
    /// Real macro would parse #[callback(realtime=true, deadline_us=1000, priority=200, cpu_affinity=[2,3])] and generate CallbackDescriptor
    pub fn register(&mut self, mut descriptor: CallbackDescriptor) -> TaskId {
        let id = TaskId(self.next_id.fetch_add(1, Ordering::SeqCst));
        descriptor.id = id;
        self.execution_stats.insert(id, ExecutionStats::new(id));
        self.tasks.insert(id, descriptor.clone());
        // For periodic tasks, push immediately to ready queue (first execution)
        if descriptor.period.is_some() {
            self.ready_queue.push(descriptor);
        }
        id
    }

    /// Manually push task to ready queue (e.g., on message arrival, timer expiry)
    pub fn wake(&mut self, task_id: TaskId) {
        if let Some(desc) = self.tasks.get(&task_id).cloned() {
            self.ready_queue.push(desc);
        }
    }

    /// Run one iteration — pops highest priority task, records execution time, deadline monitoring
    /// Returns Some((TaskId, elapsed)) if task executed, None if no ready tasks
    /// Real executor would actually call the callback function — here we simulate with closure
    pub fn run_once_with<F>(&mut self, mut callback_runner: F) -> Option<(TaskId, Duration)>
    where
        F: FnMut(&CallbackDescriptor) -> Duration, // Returns execution time
    {
        let descriptor = self.ready_queue.pop()?;
        let task_id = descriptor.id;

        let start = Instant::now();
        let elapsed = callback_runner(&descriptor);
        let _actual_elapsed = start.elapsed(); // Would compare with callback_runner's reported time vs actual for WCET analysis

        // Record stats
        if let Some(stats) = self.execution_stats.get_mut(&task_id) {
            stats.record(elapsed, descriptor.deadline);
        }

        // For periodic tasks, re-schedule based on period
        if let Some(period) = descriptor.period {
            // In real executor, would use next execution time = last + period, with deadline handling
            // For demo, just push again after period (simulated)
            // Note: This is simplified, real would need timer wheel
            let _ = period;
            // Re-queue for next period (in real, would be delayed until period elapsed)
            // For this minimal executor, we don't automatically re-queue periodic tasks — caller must wake via timer
        }

        Some((task_id, elapsed))
    }

    /// Simple run loop — runs until ready queue empty or max iterations
    /// Real executor would loop forever, handling timers, subscriptions, shutdown coordinator per DESIGN.md §15
    pub fn run_until_empty_with<F>(&mut self, mut callback_runner: F, max_iterations: usize) -> usize
    where
        F: FnMut(&CallbackDescriptor) -> Duration,
    {
        let mut executed = 0;
        while executed < max_iterations {
            if let Some(_) = self.run_once_with(|desc| callback_runner(desc)) {
                executed += 1;
            } else {
                break;
            }
        }
        executed
    }

    pub fn get_stats(&self, task_id: TaskId) -> Option<&ExecutionStats> {
        self.execution_stats.get(&task_id)
    }

    pub fn all_stats(&self) -> Vec<&ExecutionStats> {
        self.execution_stats.values().collect()
    }

    pub fn print_stats(&self) {
        println!("\n=== Executor Stats (Deadline Monitoring, not Enforcement per AUDIT) ===");
        for (id, stats) in &self.execution_stats {
            println!("Task {:?} ({}): count={}, avg={:?}, max={:?}, min={:?}, misses={}",
                id.0, self.tasks.get(id).map(|d| d.name.as_str()).unwrap_or("unknown"),
                stats.execution_count,
                stats.avg_execution_time(),
                stats.max_execution_time,
                stats.min_execution_time,
                stats.deadline_misses
            );
        }
    }
}

impl Default for Executor {
    fn default() -> Self { Self::new() }
}

// ── Realtime Lint Layer — per AUDIT Pass 15 §26 ────────────────────────────

/// Realtime lint check — would be `nros check --realtime` per DESIGN.md
/// Inspects callback source for forbidden operations in HardRealtime context
#[derive(Debug, Clone)]
pub struct RealtimeLint {
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

impl RealtimeLint {
    pub fn new() -> Self { Self { errors: Vec::new(), warnings: Vec::new() } }

    /// Check if callback contains forbidden operations for HardRealtime
    /// Real implementation would parse Rust source via syn, check for Vec, String, HashMap, Box, Arc clone, println!, format!, filesystem, blocking lock, SystemTime
    pub fn check_hard_realtime(&mut self, callback_name: &str, source_contains: &[&str]) {
        for pattern in source_contains {
            match *pattern {
                "println!" => self.errors.push(format!("ERROR RT001: HardRealtime callback {} calls std::println! — non-deterministic I/O", callback_name)),
                "Vec::new" | "Vec::push" => self.errors.push(format!("ERROR RT002: HardRealtime callback {} allocates Vec — forbidden", callback_name)),
                "String::" => self.errors.push(format!("ERROR RT002: HardRealtime callback {} allocates String", callback_name)),
                "SystemTime::now" => self.warnings.push(format!("WARNING RT003: SystemTime used in realtime path {} — should use MonotonicInstant", callback_name)),
                "HashMap" => self.errors.push(format!("ERROR RT004: HardRealtime callback {} uses HashMap — may allocate", callback_name)),
                _ => {}
            }
        }
    }

    pub fn has_errors(&self) -> bool { !self.errors.is_empty() }

    pub fn print(&self) {
        for e in &self.errors { println!("{}", e); }
        for w in &self.warnings { println!("{}", w); }
        if self.errors.is_empty() {
            println!("Realtime lint: No hard realtime violations found (for checked patterns)");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_executor_priority_ordering() {
        let mut executor = Executor::new();
        let low = CallbackDescriptor { id: TaskId(0), name: "low".into(), execution_class: ExecutionClass::Normal, priority: 10, deadline: None, period: None, cpu_affinity: None };
        let high = CallbackDescriptor { id: TaskId(0), name: "high".into(), execution_class: ExecutionClass::HardRealtime, priority: 200, deadline: Some(Duration::from_micros(1000)), period: None, cpu_affinity: None };

        let low_id = executor.register(low);
        let high_id = executor.register(high);

        // Manually wake both
        executor.wake(low_id);
        executor.wake(high_id);

        // High priority should run first
        let first = executor.run_once_with(|_| Duration::from_micros(10)).unwrap();
        assert_eq!(first.0, high_id);

        let second = executor.run_once_with(|_| Duration::from_micros(10)).unwrap();
        assert_eq!(second.0, low_id);
    }

    #[test]
    fn test_executor_deadline_monitoring() {
        let mut executor = Executor::new();
        let desc = CallbackDescriptor {
            id: TaskId(0),
            name: "control_loop".into(),
            execution_class: ExecutionClass::HardRealtime,
            priority: 200,
            deadline: Some(Duration::from_micros(1000)),
            period: Some(Duration::from_millis(1)),
            cpu_affinity: Some(vec![2,3]),
        };
        let id = executor.register(desc);
        executor.wake(id);

        // Simulate callback taking 1.5ms > 1ms deadline
        executor.run_once_with(|_| Duration::from_micros(1500));

        let stats = executor.get_stats(id).unwrap();
        assert_eq!(stats.deadline_misses, 1);
        assert_eq!(stats.execution_count, 1);
    }

    #[test]
    fn test_realtime_lint() {
        let mut lint = RealtimeLint::new();
        lint.check_hard_realtime("control_loop", &["println!", "Vec::new"]);
        assert!(lint.has_errors());
        assert!(lint.errors.iter().any(|e| e.contains("RT001")));
        assert!(lint.errors.iter().any(|e| e.contains("RT002")));
    }
}
